---
title: "Práctico 1"
subtitle: "Psicoestadística - Facultad de Educación - UCC"
output: 
  pdf_document:
    includes:
      in_header: ../header.tex
      # before_body: doc.prefix.tex
    df_print: kable
    fig_caption: yes
urlcolor: blue
breaklinks: true
fontsize: 12pt
---
## Primera Parte
```{r setoptions, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE)
library(knitr)
library(ggplot2)
library(dplyr)
library(tidyr)
usuindividual <- read.csv2("../data/usu_individual_t117.txt")
usuhogar <- read.csv2("../data/usu_hogar_t117.txt")
cuestionario <- read.csv2("../data/cuestionario.csv")
```

En las siguientes actividades se trabajará principalmente con información extraída de las siguientes bases de datos.  

* Base de datos de una encuesta de evaluación de CEPRAM. CEPRAM (Centro de Promoción del Adulto Mayor) es una fundación destinada a la promoción de la salud de los adultos mayores. Una de las actividades principales desarrollada por CEPRAM es el dictado de cursos en distintas áreas de conocimiento. (Para más información ver [www.cepram.org.ar](www.cepram.org.ar)) Su utilización se realiza con permiso de CEPRAM.  

* Base de datos de la Ecuesta Permanente de Hogares (EPH) realizada por el Instituto Nacional de Estadística y Censos (INDEC) correspondiente al primer trimestre de 2017. EPH es un programa nacional de producción sistemática y permanente de indicadores sociales, que permite conocer las características sociodemográficas y socioeconómicas de la población. Es una base de datos de acceso público. <http://www.indec.gob.ar/bases-de-datos.asp>.


## Actividades
1. Se desea realizar un estudio para determinar que variables están relacionadas y predicen mejor el rendimiento escolar en alumnos de una escuela primaria de la Ciudad de Córdoba. Para ello se seleccionó aleatoriamente una muestra de alumnos de dicha escuela. Se evaluaron las siguientes variables: condición socioeconómica de los padres, nivel educativo de los padres, región de procedencia, índice de IQ. Identifique la unidad de análisis y las variables en dicho estudio.

2. Se desea realizar un estudio para comparar el rendimiento académico entre escuelas públicas y privadas en la ciudad de Córdoba. Para ello se seleccionaron al azar 25 colegios privados y 25 colegios públicos. Se evaluó el promedio histórico y el puntaje obtenido en el Plan Aprender (Plan Nacional de Evaluación Educativa) en las diferentes areas de conocimiento. Identifique unidad de análisis y la variables en dicho estudio.

3. Determine los niveles de medición de las siguientes variables. Indique, adicionalmente, que valores puede tomar cada una (p ej. la variable año de nacimiento no tiene un límite inferior definido, sin embargo el límite superior no puede ser mayor al año actual)

Base EPH:

* Sexo
    1. Varón
    2. Mujer
    
* Año de nacimiento
* Nivel educativo:
    1. Primaria Incompleta (incluye educación especial)
    2. Primaria Completa
    3. Secundaria Completa
    5. Superior Universitaria Incompleta
    6. Superior Universitaria Completa
* Cuanto tiempo hace que trabaja en su empleo actual

* Cuánto cobró en el último mes

Base CEPRAM:  

* Cómo está usted de satisfecho con su vida:
    1. Nada
    2. Algo
    3. Bastante
    4. Mucho
    5. Totalmente

* ¿Cuántas veces ha ido al médico en el último mes?

* Indique su nivel de acuerdo. Uno de los principales motivos para acercarse al CEPRAM fue hacer amigos, insertarse en un grupo:
    1. Nada importante
    2. Poco importante
    3. Importante
    4. Muy importante

4. Si somos estrictos, las siguientes variables están mal definidas. Justifique por qué, considerando las nociones de **exhaustividad** y **exclusión mutua**.

* Nivel Educativo Alcanzado
    1. Primario
    2. Universitario
    
* Ocupación actual
    1. Estudia
    2. Trabaja
    3. Desocupado


## Segunda Parte

1. Diríjase al siguiente link https://datosestadistica.cba.gov.ar/dataset/indicadores-del-ra-de-educacion y descargue el Anuario del Ministerio de Educación del Año 2016 de la provincia de Córdoba. 
Responda las siguientes preguntas:  

     a) ¿Cuál es el total de alumnos matriculados en escuelas especiales en la provincia de Córdoba? ¿Cuál es el total para cada uno de los niveles: Inicial, Primario y Secundario? (Pag 159 y pag 164) Calcule las cantidades a partir de la distribución porcentual de la matrícula en escuelas especiales (pag. 164). 
     b) Calcule el porcentaje de alumnos matriculados en colegios especiales con el total matriculado en los niveles inicial, primario y secundario. (Pág 15)
     c) Queremos saber cómo ha sido la integración de alumnos de colegios especiales a colegios comunes. Analice los gráficos de la página 166. Interprete. ¿La integración aumentó o disminuyó entre los años 2012 y 2016? ¿Cómo a sido esa evolución en los colegios públicos y en los colegios privados?  
     d) Diríjase a las páginas 168 y 169. Calcule los porcentajes de alumnos que reciben integración de tipo **simultánea** y **apoyo** para los años 2012 y 2016, en relación al total de alumnos integrados. Compare y describa la variación de esos porcentajes a lo largo de esos años.
 

2. Ingrese a <http://datos.gob.ar/dataset/modernizacion-puntos-digitales> y descargue la base de datos Ubicación de Puntos Digitales, en formato .csv. Especificaciones del archivo: separado por ','; decimal: '.'; primer fila como encabezado.
Los Puntos Digitales forman parte de las políticas de inclusión tecnológica desarrolladas por el Ministerio de Modernización, a través del Plan País Digital.
Es un espacio público de inclusión digital que brinda conectividad, capacitaciones y acceso a las nuevas Tecnologías de la Información y de la Comunicación (TIC). Abra el archivo y observe la base de datos que ha descargado. Note que es una matriz de datos primaria. Cada fila es una unidad de observación y cada columna es una variable. Responda:

    a) ¿Cuántas variables hay en esta tabla? ¿Cántos puntos digitales hay en total?

    b) Realice una tabla de distribución de frecuencias para la variable provincia. ¿Cuál es la provincia que tiene más puntos digitales? ¿Cuál es la que tiene menos? ¿Qué nivel de medición tiene la variable provincia?

    c) Realice una tabla de distribución de frecuencias para la variable estado. ¿Cuál es el porcentaje de puntos digitales que se encuentra activo?
